# Production Environment Configuration for Submissions
# Optimized for maximum performance and reliability

# =============================================================================
# PRODUCTION SUBMISSION STRATEGY CONFIGURATION
# =============================================================================
submission_strategies:
  baseline:
    model_config:
      prophet_config:
        daily_seasonality: true
        weekly_seasonality: true
        yearly_seasonality: true
        changepoint_prior_scale: 0.01  # More conservative
        changepoint_range: 0.9
        seasonality_prior_scale: 10.0
        holidays_prior_scale: 10.0
        n_changepoints: 25  # More granular
        mcmc_samples: 0  # Use MAP estimation for speed
        uncertainty_samples: 1000
    risk_tolerance: low
    post_processing_enabled: true
    validation_strategy: rigorous_cv

  single_model:
    model_config:
      lightgbm_config:
        num_leaves: 63  # Increased for production
        learning_rate: 0.05  # More conservative
        feature_fraction: 0.9
        bagging_fraction: 0.9
        bagging_freq: 5
        verbose: -1
        early_stopping_rounds: 200  # More patience
        n_estimators: 5000  # Much higher for production
        max_depth: 8
        min_child_samples: 100
        subsample: 0.9
        colsample_bytree: 0.9
        reg_alpha: 0.1
        reg_lambda: 0.1
        random_state: 42
    risk_tolerance: medium
    post_processing_enabled: true
    validation_strategy: time_series_cv

  ensemble:
    model_config:
      ensemble_config:
        models: ["lightgbm", "prophet", "catboost", "xgboost"]  # Full ensemble
        ensemble_method: "stacking"
        meta_learner: "ridge_regression"
        meta_cv_folds: 10
        use_feature_stacking: true
        blend_weights_optimization: true
    risk_tolerance: medium
    post_processing_enabled: true
    validation_strategy: stacking_cv

  optimized_ensemble:
    model_config:
      optimized_ensemble_config:
        models: ["lightgbm", "prophet", "catboost", "xgboost", "arima", "exponential_smoothing"]
        optimization_method: "optuna"
        n_trials: 500  # Extensive optimization
        cv_folds: 10
        optimization_timeout_hours: 12
        pruning_enabled: true
        study_direction: "minimize"
        sampler: "TPESampler"
        early_stopping_patience: 50
    risk_tolerance: high
    post_processing_enabled: true
    validation_strategy: leaderboard_cv

  final:
    model_config:
      final_config:
        use_best_model: true
        ensemble_all_previous: true
        final_optimization: true
        max_optimization_time_minutes: 120  # Extensive final optimization
        ensemble_all_strategies: true
        final_blending_method: "optuna_weighted"
        cross_validation_folds: 15
        final_feature_selection: true
        final_hyperparameter_tuning: true
    risk_tolerance: high
    post_processing_enabled: true
    validation_strategy: final_validation

# =============================================================================
# PRODUCTION RISK MANAGEMENT CONFIGURATION
# =============================================================================
risk_management:
  enable_overfitting_assessment: true
  enable_complexity_assessment: true
  enable_leakage_assessment: true
  enable_execution_assessment: true

  overfitting_config:
    max_acceptable_gap: 0.05  # Very strict
    severe_gap_threshold: 0.1
    weight: 2.0  # High weight for production

  complexity_config:
    max_safe_features: 2000  # Higher for production
    max_safe_depth: 25
    max_training_time_minutes: 180  # Generous for production
    weight: 1.0

  leakage_config:
    suspicious_score_threshold: 0.92  # Strict threshold
    weight: 3.0  # Very high weight

  execution_config:
    max_memory_gb: 32  # Higher for production
    max_prediction_time_seconds: 600  # More generous
    weight: 1.5

  # Strict risk level thresholds for production
  risk_thresholds:
    low: 0.2
    medium: 0.5
    high: 0.7

# =============================================================================
# PRODUCTION COMPETITIVE ANALYSIS CONFIGURATION
# =============================================================================
competitive_analysis:
  leaderboard_config:
    top_tier_size: 3
    contender_tier_size: 10
    improvement_buffer: 0.02  # Very small buffer

  timeline_analysis:
    critical_days_remaining: 3
    urgent_days_remaining: 7
    planning_days_remaining: 14

  strategic_positioning:
    leader_strategy: conservative
    contender_strategy: aggressive
    middle_pack_strategy: balanced
    bottom_tier_strategy: catch_up

  advanced_analysis:
    competitor_modeling: true
    gap_forecasting: true
    risk_adjusted_targeting: true
    monte_carlo_simulations: 1000

# =============================================================================
# PRODUCTION TIMELINE MANAGEMENT CONFIGURATION
# =============================================================================
timeline_management:
  deadline_tracker:
    upcoming_alert_hours: 48  # Earlier alerts
    urgent_alert_hours: 12
    critical_alert_hours: 4

  submission_windows:
    baseline:
      day: 14
      optimal_hour: 20  # Evening submission
      duration_hours: 8
      priority: low
      buffer_hours: 4

    single_model:
      day: 10
      optimal_hour: 22
      duration_hours: 12
      priority: medium
      buffer_hours: 4

    initial_ensemble:
      day: 7
      optimal_hour: 20
      duration_hours: 18
      priority: medium
      buffer_hours: 6
      dependencies: ["single_model"]

    optimized_ensemble:
      day: 3
      optimal_hour: 18
      duration_hours: 24
      priority: high
      buffer_hours: 8
      dependencies: ["initial_ensemble"]

    final_submission:
      day: -1  # Competition deadline
      optimal_hour: 15  # 3 PM, well before deadline
      duration_hours: 72  # Very generous window
      priority: critical
      buffer_hours: 9  # Large safety buffer
      dependencies: ["optimized_ensemble"]

# =============================================================================
# PRODUCTION POST-PROCESSING CONFIGURATION
# =============================================================================
post_processing:
  business_rules:
    enabled: true
    min_value: 0.0
    max_growth_rate: 1.5  # Conservative for production
    enable_seasonality_constraints: true
    enable_non_negativity: true
    enable_trend_constraints: true
    weight: 1.5

  outlier_capping:
    enabled: true
    method: quantile
    lower_quantile: 0.001  # Very conservative
    upper_quantile: 0.999
    iqr_factor: 1.5
    zscore_threshold: 3.0
    weight: 1.2

  seasonal_adjustment:
    enabled: true
    groupby_columns: ["store_id", "product_id"]
    seasonal_periods: [7, 14, 30, 365]
    decomposition_method: "seasonal_decompose"
    weight: 0.8

  ensemble_blending:
    enabled: true
    smoothing_factor: 0.05  # Very conservative
    blending_method: exponential_smoothing
    window_size: 14  # Longer window
    weight: 0.6

  advanced_post_processing:
    enabled: true
    anomaly_detection: true
    trend_adjustment: true
    external_factors_adjustment: true
    confidence_weighted_blending: true

# =============================================================================
# PRODUCTION SUBMISSION PIPELINE CONFIGURATION
# =============================================================================
submission_pipeline:
  steps:
    data_validation:
      enabled: true
      min_train_size: 10000  # Much higher for production
      min_test_size: 1000
      data_quality_checks: true
      feature_stability_checks: true

    model_training:
      enabled: true
      timeout_minutes: 240  # Generous for production
      checkpoint_enabled: true
      distributed_training: true

    risk_assessment:
      enabled: true
      max_risk_threshold: 0.6  # Strict for production
      detailed_assessment: true

    competitive_analysis:
      enabled: true
      require_leaderboard: true
      detailed_analysis: true

    post_processing:
      enabled: true
      validation_enabled: true

    submission_execution:
      enabled: true
      max_risk_threshold: 0.6
      backup_submission: true
      submission_validation: true

# =============================================================================
# PRODUCTION PERFORMANCE AND MONITORING
# =============================================================================
performance:
  max_memory_usage_gb: 64  # High for production
  max_execution_time_minutes: 480  # Very generous
  enable_performance_monitoring: true
  enable_resource_alerts: true
  enable_distributed_computing: true
  gpu_acceleration: true

monitoring:
  enable_mlflow_logging: true
  log_predictions: true
  log_feature_importance: true
  log_risk_assessment: true
  log_competitive_analysis: true
  enable_model_versioning: true
  enable_experiment_comparison: true
  enable_automated_reporting: true

# =============================================================================
# PRODUCTION OUTPUT AND REPORTING
# =============================================================================
output:
  submission_format:
    required_columns: ["store_id", "product_id", "date", "prediction"]
    decimal_places: 6  # High precision for production
    compression: true  # Enable for large files

  reporting:
    generate_summary_report: true
    include_risk_analysis: true
    include_competitive_analysis: true
    save_intermediate_results: true
    generate_confidence_intervals: true
    include_model_explanability: true

# =============================================================================
# PRODUCTION FEATURE FLAGS
# =============================================================================
feature_flags:
  enable_advanced_risk_assessment: true
  enable_competitive_intelligence: true
  enable_timeline_management: true
  enable_advanced_post_processing: true
  enable_final_optimization: true
  enable_submission_validation: true
  enable_ensemble_diversity: true
  enable_automated_feature_engineering: true
  enable_model_stacking: true
  enable_hyperparameter_optimization: true

# =============================================================================
# PRODUCTION COMPETITION-SPECIFIC SETTINGS
# =============================================================================
competition:
  name: "Hackathon Forecast 2025 - Production"
  primary_metric: "wmape"
  metric_direction: "minimize"
  submission_limit: 5
  team_size_limit: 5

  # Ambitious performance targets for production
  performance_targets:
    excellent_wmape: 12.0
    good_wmape: 15.0
    acceptable_wmape: 20.0

  # Full timeline for production
  phases:
    exploration:
      days: 5
      focus: "data_understanding"
    development:
      days: 7
      focus: "model_development"
    optimization:
      days: 3
      focus: "performance_optimization"
    final:
      days: 1
      focus: "final_submission"

# =============================================================================
# PRODUCTION-SPECIFIC SETTINGS
# =============================================================================
production:
  # Resource optimization
  resource_management:
    enable_memory_optimization: true
    enable_cpu_optimization: true
    enable_gpu_utilization: true
    parallel_processing: true
    max_workers: 8

  # Model persistence
  model_persistence:
    save_all_models: true
    model_compression: true
    versioning_enabled: true
    backup_models: true

  # Security and reliability
  security:
    enable_input_validation: true
    enable_output_validation: true
    secure_model_storage: true
    audit_logging: true

  # Quality assurance
  quality_assurance:
    enable_model_testing: true
    enable_prediction_validation: true
    enable_performance_regression_testing: true
    enable_automated_quality_checks: true

  # Disaster recovery
  disaster_recovery:
    enable_checkpointing: true
    enable_automatic_recovery: true
    backup_frequency_minutes: 30
    retain_backup_days: 7